### PR TITLE
Maximum Redirection Support

### PR DESCRIPTION
**Pull request by ngetchell**
Added the ability to set the max redirection for web requests.

### CODE REVIEW

**Comment by ngetchell** [comment]
Thought I would bring some more curl arguments over.

**Comment by cdhunt** [comment]
Thank you for that and including a test as well!

**Comment by ngetchell** [comment]
Should I keep them coming?

**Comment by cdhunt** [comment]
Please do. Just please bump the version in the module manifest with each PR. That will speed up the automated deployment to PowerShellGallery.com

**Pull request merged**
